Added Rakuten's Viki streaming service
AdguardTeam/HostlistsRegistry pull request #128
Opened 2022-12-31 16:02 UTC by sandervankasteel

2023-01-02 17:44 UTC, ameshkov requested changes

2023-01-02 17:44 UTC, ameshkov commented on assets/services.json
> +      "icon_svg": "<svg xmlns=\"http://www.w3.org/2000/svg\" fill=\"currentColor\" viewBox=\"0 0 8.996 8.996\"><circle r=\"4.498\" cy=\"4.498\" cx=\"4.497\" fill=\"#0c9bff\"/><path d=\"M3.915 6.932V5
Wrong logo, use this instead:
```
<svg xmlns="http://www.w3.org/2000/svg"  viewBox="0 0 50 50"><path d="M 5 5 L 5 45 L 45 45 L 45 5 L 5 5 z M 19.435547 14 L 19.4375 14 L 20.587891 14 L 20.587891 17.21875 L 21.929688 15.570312 L 23.496094 15.570312 L 21.578125 17.789062 L 23.802734 20.302734 L 22.236328 20.302734 L 20.587891 18.357422 L 20.587891 20.302734 L 19.435547 20.302734 L 19.435547 14 z M 10.001953 14.390625 L 11.933594 14.390625 C 13.105594 14.390625 14.056641 15.304687 14.056641 16.429688 C 14.056641 17.114687 13.701109 17.719797 13.162109 18.091797 L 14.892578 20.302734 L 13.427734 20.302734 L 11.996094 18.470703 L 11.169922 18.470703 L 11.169922 20.302734 L 10.001953 20.302734 L 10.001953 14.390625 z M 28.746094 14.390625 L 29.865234 14.390625 L 29.865234 15.568359 L 30.820312 15.568359 L 30.820312 16.691406 L 29.865234 16.691406 L 29.865234 18.716797 C 29.865234 19.163797 30.210578 19.298828 30.392578 19.298828 C 30.538578 19.298828 30.665625 19.246641 30.765625 19.181641 L 31.501953 20.123047 C 31.150953 20.323047 30.719203 20.421875 30.408203 20.421875 C 29.574203 20.421875 28.746094 19.791375 28.746094 18.734375 L 28.746094 16.691406 L 28.154297 16.691406 L 28.154297 15.570312 L 28.15625 15.570312 L 28.746094 15.570312 L 28.746094 14.390625 z M 33.347656 15.449219 C 34.620656 15.449219 35.762281 16.566578 35.488281 18.267578 L 32.269531 18.267578 C 32.416531 19.349578 33.688172 19.898406 34.451172 18.816406 L 35.439453 19.363281 C 34.804453 20.229281 34.048984 20.423828 33.458984 20.423828 C 32.290984 20.423828 31.126953 19.401547 31.126953 17.935547 C 31.126953 16.541547 32.053656 15.449219 33.347656 15.449219 z M 16.628906 15.453125 C 17.041906 15.453125 17.344641 15.573297 17.681641 15.779297 L 17.681641 15.570312 L 18.800781 15.570312 L 18.800781 20.302734 L 17.681641 20.302734 L 17.681641 20.09375 C 17.344641 20.29975 17.042906 20.419922 16.628906 20.419922 C 15.357906 20.419922 14.392578 19.3055 14.392578 17.9375 C 14.391578 16.5695 15.356906 15.453125 16.628906 15.453125 z M 38 15.453125 C 39.187 15.453125 40 16.379484 40 17.521484 L 40 20.302734 L 38.882812 20.302734 L 38.882812 17.521484 C 38.882812 17.000484 38.509797 16.560547 37.966797 16.560547 C 37.423797 16.560547 37.050781 17.000484 37.050781 17.521484 L 37.050781 20.302734 C 37.050781 20.302734 35.931641 20.303734 35.931641 20.302734 L 35.931641 15.570312 L 37.050781 15.570312 L 37.050781 15.744141 C 37.050781 15.744141 37.45 15.453125 38 15.453125 z M 11.169922 15.513672 L 11.169922 17.345703 L 11.931641 17.345703 C 12.456641 17.346703 12.886719 16.936688 12.886719 16.429688 C 12.886719 15.924687 12.456641 15.513672 11.931641 15.513672 L 11.169922 15.513672 z M 23.685547 15.570312 L 24.802734 15.570312 L 24.802734 18.351562 C 24.802734 18.872563 25.17575 19.314453 25.71875 19.314453 C 26.26175 19.314453 26.634766 18.872563 26.634766 18.351562 L 26.634766 15.570312 L 27.753906 15.570312 L 27.753906 20.304688 L 26.634766 20.304688 L 26.634766 20.128906 C 26.634766 20.128906 26.235547 20.421875 25.685547 20.421875 C 24.498547 20.421875 23.685547 19.493562 23.685547 18.351562 L 23.685547 15.570312 z M 33.324219 16.470703 C 32.877344 16.478703 32.428047 16.772172 32.310547 17.326172 L 34.324219 17.326172 C 34.215219 16.740172 33.771094 16.462703 33.324219 16.470703 z M 16.628906 16.59375 C 16.001906 16.59375 15.542969 17.1885 15.542969 17.9375 C 15.542969 18.6875 16.001906 19.279297 16.628906 19.279297 C 17.255906 19.279297 17.698219 18.6865 17.699219 17.9375 C 17.699219 17.1875 17.255906 16.59375 16.628906 16.59375 z M 16.240234 21.587891 L 34.472656 21.587891 L 17.693359 23.046875 L 16.240234 21.587891 z M 10 25.466797 L 13.179688 25.466797 L 15.326172 32.365234 L 17.441406 25.466797 L 20.607422 25.466797 L 16.578125 36 L 14.074219 36 L 10 25.466797 z M 21.617188 25.466797 L 24.628906 25.466797 L 24.628906 36 L 21.617188 36 L 21.617188 25.466797 z M 26.335938 25.466797 L 29.347656 25.466797 L 29.347656 29.470703 L 32.681641 25.466797 L 36.078125 25.466797 L 32.095703 30.183594 L 36.355469 36 L 32.896484 36 L 30.179688 32.126953 L 29.347656 32.957031 L 29.347656 36 L 26.335938 36 L 26.335938 25.466797 z M 36.988281 25.466797 L 40 25.466797 L 40 36 L 36.988281 36 L 36.988281 25.466797 z"/></svg>
```

2023-01-02 17:45 UTC, ameshkov requested changes

2023-01-02 17:45 UTC, ameshkov commented on assets/services.json
> +      "id": "viki",
I'd prefer a longer ID

```suggestion
      "id": "rakuten_viki",
```

2023-01-02 21:59 UTC, sandervankasteel commented on assets/services.json
> +      "id": "viki",
Will do :+1:

2023-01-06 17:18 UTC, ameshkov approved these changes

2023-01-06 17:18 UTC, merged