Add ShadowWhisperer's Malware list
AdguardTeam/HostlistsRegistry pull request #204
Opened 2023-04-13 15:42 UTC by Sergey-Lyapin

https://github.com/AdguardTeam/HostlistsRegistry/issues/202

2023-04-19 10:49 UTC, Alex-302 requested changes

2023-04-19 10:49 UTC, Alex-302 commented on filters/security/filter_42_ShadowWhisperersMalwareList/configuration.json
> +    "homepage": "https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Malware",
the home page of the repo

```suggestion
    "homepage": "https://github.com/ShadowWhisperer/BlockLists",
```

2023-04-19 10:49 UTC, Alex-302 commented on filters/security/filter_42_ShadowWhisperersMalwareList/metadata.json
> +    "homepage": "https://github.com/ShadowWhisperer/BlockLists/blob/master/Lists/Malware",
the home page of the repo

```suggestion
    "homepage": "https://github.com/ShadowWhisperer/BlockLists",
```

2023-04-20 10:25 UTC, Alex-302 approved these changes

2023-04-20 10:36 UTC, zloyden approved these changes

2023-04-20 13:36 UTC, merged

2023-04-20 18:36 UTC, ameshkov commented on filters/security/filter_42_ShadowWhisperersMalwareList/configuration.json
> +        "source": "https://raw.githubusercontent.com/ShadowWhisperer/BlockLists",
Leads to 404