Update configuration.json
AdguardTeam/HostlistsRegistry pull request #211
Opened 2023-04-22 23:58 UTC by KnightmareVIIVIIXC

Exclude localhost.localdomain

2023-05-06 00:19 UTC, KnightmareVIIVIIXC reviewed
exclude localhost.localdomain

2023-06-09 11:38 UTC, Sergey-Lyapin approved these changes

2023-06-09 11:45 UTC, Sergey-Lyapin requested changes

2023-06-09 11:45 UTC, Sergey-Lyapin commented on filters/general/filter_4_DanPollocksList/configuration.json
>        ]
Hello, @KnightmareVIIVIIXC

The comma is forgotten here.

2023-06-09 20:59 UTC, Sergey-Lyapin commented on filters/general/filter_4_DanPollocksList/configuration.json
>        ]
I added it myself, I hope you don't mind.

2023-06-09 21:00 UTC, Sergey-Lyapin approved these changes

2023-06-09 21:00 UTC, merged