Add Amazon Streaming as a blockable service
AdguardTeam/HostlistsRegistry pull request #424
Opened 2023-12-21 16:19 UTC by Sergey-Lyapin

https://github.com/AdguardTeam/HostlistsRegistry/issues/301

Suggestions about domains and icons are welcome.

2023-12-21 18:35 UTC, Alex-302 requested changes

2023-12-21 18:35 UTC, Alex-302 commented on services/amazon_streaming.yml
> +  - '||pv-cdn.net^'
Not sure about CDNs
aiv-cdn.net
pv-cdn.net
I am sure the rest of the domains are enough to block related services.

2023-12-22 17:51 UTC, Alex-302 approved these changes

2024-01-24 13:53 UTC, Alex-302 commented
@Sergey-Lyapin

2024-01-25 07:39 UTC, zloyden approved these changes

2024-01-25 12:06 UTC, merged