Added more TikTok domains
AdguardTeam/HostlistsRegistry pull request #465
Opened 2024-03-06 15:02 UTC by DandelionSprout

My memory is scarce, but I remember finding these domains roughly 9 months ago, and they primarily apply to Douyin's website's video pages.

2024-03-07 18:26 UTC, Alex-302 requested changes
Checked using urlscan.io It seems all good, except one.

2024-03-07 18:26 UTC, Alex-302 commented on services/tiktok.yml
> +  - '||bytescm.com^'
lf-cdn-tos.bytescm.com

2024-03-07 18:26 UTC, Alex-302 commented on services/tiktok.yml
> +  - '||bytegoofy.com^'
lf1-cdn-tos.bytegoofy.com

2024-03-07 18:26 UTC, Alex-302 commented on services/tiktok.yml
> +  - '||feelgood.cn^'
api.feelgood.cn - it seems not related to TT

2024-03-10 03:15 UTC, DandelionSprout commented
All I can tell for sure, was that I found them while browsing Douyin on a dare from someone who wanted me to check out cartoon videos there, and considering it was Douyin and that I'm pro-'Republic of China', I took the "Let's block virtually every feasible script on their video pages".

As a result of those circumstances, I fully believe you in that those 3 domains you list as good, indeed are good.

2024-03-13 14:23 UTC, Sergey-Lyapin commented
Hi @DandelionSprout, please remove `api.feelgood.cn` and we will merge.

2024-03-14 04:27 UTC, DandelionSprout commented
After doublechecking what else was in their subdomains, `api.` seems to the least used among `feelgood.cn`'s 6 subdomains, so I'll remove that entry entirely.

2024-03-14 17:46 UTC, Alex-302 approved these changes

2024-03-14 17:46 UTC, merged