Add some En localisations
AdguardTeam/HostlistsRegistry pull request #547
Opened 2024-10-10 17:31 UTC by Sergey-Lyapin

2024-10-10 17:46 UTC, slavaleleka approved these changes

2024-10-10 18:32 UTC, Alex-302 approved these changes

2024-10-11 05:56 UTC, AdamWr approved these changes

2024-10-11 06:08 UTC, zloyden approved these changes

2024-10-11 13:08 UTC, el-termikael requested changes

2024-10-11 13:08 UTC, el-termikael commented on locales/en/filters.json
> +		"hostlist.57.description": "Blocks dating sites."
лучше websites

2024-10-11 13:08 UTC, el-termikael commented on locales/en/filters.json
> +		"hostlist.61.description": "Blocks Samsung native broadband tracker that track your activity."
```suggestion
"hostlist.61.description": "Blocks Samsung native broadband trackers that track your activity."

2024-10-11 13:08 UTC, el-termikael commented on locales/en/filters.json
> +		"hostlist.62.description": "Filter of malicious web resources (phishing, online fraud, malware, etc.) targeting Ukrainian citizens"
```suggestion
"hostlist.62.description": "Filters malicious web resources (phishing, online fraud, malware, etc.) targeting Ukrainian citizens"

2024-10-11 13:08 UTC, el-termikael commented on locales/en/filters.json
> +		"hostlist.63.description": "Blocks Windows/Office native broadband tracker that track your activity."
trackers

2024-10-11 13:44 UTC, el-termikael approved these changes

2024-10-11 13:55 UTC, slavaleleka approved these changes

2024-10-11 13:56 UTC, el-termikael approved these changes

2024-10-31 11:19 UTC, Alex-302 approved these changes

2024-10-31 11:21 UTC, zloyden approved these changes

2024-10-31 11:27 UTC, SeverAnna approved these changes

2024-10-31 11:28 UTC, zloyden approved these changes

2024-10-31 11:29 UTC, Alex-302 approved these changes

2024-10-31 11:29 UTC, merged